#gui test
URL=input("Enter a website URL: \n\n")
while True:
    print(f"            WEBSITE TOOL KIT FOR {URL}          ")
    print("----------------------------------------------\n")
    print("-        1.  Analyze                         -\n")
    print("-        2. Pen Test                         -\n")
    print("-        3. complete Test                   -\n")
    print("-                                            -\n")
    print("-                                            -\n")
    print("-                                            -\n")
    print("----------------------------------------------\n")

    option= input("Select tool: ")

    if option == "1":
        print(f"--------------Analyze {URL}--------------------\n")
        print("-        1.SEO Analysis                      -\n")
        print("-        2. Security Scan                    -\n")
        print("-        3. Peformace                        -\n")
        print("-        4. Total                            -\n")
        print("-                                            -\n")
        print("-                                            -\n")
        print("----------------------------------------------\n")
        option= input("Enter option: ")
        print(f"RUNNING {option}")
    elif option == "2":
        print(f"--------------Pen Test {URL}--------------------\n")
        print("-        1.SQL Injection                     -\n")
        print("-        2.XSS                               -\n")
        print("-        3. CSRF                             -\n")
        print("-        4. Total                            -\n")
        print("-                                            -\n")
        print("-                                            -\n")
        print("----------------------------------------------\n")
        option= input("Enter option: ")
        print(f"RUNNING {option}")
    elif option == "3":
        print(f"--------------Total test {URL}--------------------\n")
        print("-                                            -\n")
        print("-                                            -\n")
        print("-           Running TOTAL TEST               -\n")
        print("-                                            -\n")
        print("-                                            -\n")
        print("-                                            -\n")
        print("----------------------------------------------\n")
